
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using DynamicData.Kernel;
using Mutagen.Bethesda;
using Mutagen.Bethesda.FormKeys.SkyrimSE;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Noggog;
using System.Text.RegularExpressions;
using System.Reflection;
using System.Reflection.Metadata;
using CommandLine;
using System.Linq;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Skyrim;
using ScriptProperty = Mutagen.Bethesda.Skyrim.ScriptProperty;
using VirtualMachineAdapter = Mutagen.Bethesda.Skyrim.VirtualMachineAdapter;
using IQuest = Mutagen.Bethesda.Skyrim.IQuest;
using System.Collections;
using DynamicData;
using Newtonsoft.Json;


// Function to initialize the matches dictionary with all keys set to 0


namespace MadAborManual;

public class Program
{
    private static Lazy<Settings> formSettings = null!;

    static void WriteToIniFile(string filePath, string text)
    {
        // Open the file for appending
        using (StreamWriter writer = new StreamWriter(filePath, true, Encoding.UTF8))
        {
            // Write the text to the file
            writer.WriteLine(text);
        }
    }
    static void ClearFile(string filePath)
    {
        // Open the file for writing and clear its content
        using (StreamWriter writer = new StreamWriter(filePath, false, Encoding.UTF8))
        {
            // Write nothing to the file (effectively clearing its content)
        }
    }
    static DataTable CreateDataTableFromCsv(string filePath)
    {
        DataTable dataTable = new DataTable();

        // Read all lines from the CSV file
        string[] lines = File.ReadAllLines(filePath);

        if (lines.Length > 0)
        {
            // Determine the number of columns based on the first line
            string[] firstLineValues = lines[0].Split(',');

            // Add generic column names (Column1, Column2, etc.)
            for (int col = 0; col < firstLineValues.Length; col++)
            {
                dataTable.Columns.Add("Column" + (col + 1));
            }

            // Add all rows starting from the first line
            foreach (string line in lines)
            {
                string[] values = line.Split(',');
                dataTable.Rows.Add(values);
            }
        }

        return dataTable;
    }


    public static Task<int> Main(string[] args)
    {
        return SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings(
                "Settings",
                "Settings.json",
                out formSettings)
            .SetTypicalOpen(GameRelease.SkyrimSE, "unofficialReqtificatorLite.esp")
            .Run(args);
    }

    public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {



        foreach (var spell in state.LoadOrder.PriorityOrder.Spell().WinningOverrides())
        {
            var isagoodspell = false;
            var formstring = "00080A:SpellAbsorptionRework.esp";
            var firstEffect = spell.Effects.FirstOrDefault();
            try
            {
                if (firstEffect != null && firstEffect.Data != null)
                {
                    IFormLinkGetter<IMagicEffectGetter> effectLink = firstEffect.BaseEffect;
                    var effectLinkGetter = effectLink.Resolve(state.LinkCache);

                    // If the archetype is "Script", skip this spell entirely
                    if (effectLinkGetter.Archetype.Type.ToString() == "Script")
                    {
                        //Console.WriteLine(effectLinkGetter.Archetype.Type.ToString());
                        // Skip to the next spell
                        continue;
                    }
                    if (effectLinkGetter.Flags.HasFlag(MagicEffect.Flag.Hostile) == false)
                    {
                        continue;
                    }
                    //Console.WriteLine(effectLinkGetter.Archetype.Type.ToString());
                }
                // At this point we KNOW we want to modify this spell

                // Make a copy of the first effect so we get its magnitude/area/duration, etc.

                if (!string.IsNullOrEmpty(spell.EditorID) &&
spell.EditorID.ToString().IndexOf("trap", StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    continue; // Skip this spell entirely
                }
            }
            catch (Exception ex) {
                continue;
            }



            //var spellMagickaPerLevel = new FormLink<ISpellGetter>(FormKey.Factory("0008A9:RequiemPatcherKeyword.esp"));
            //    IFormLinkGetter<ISpellRecordGetter> spellMagickaPerLevelLink = spellMagickaPerLevel;
            //    var spellMagickaPerLevelGetter = spellMagickaPerLevelLink.Resolve(state.LinkCache);
            //    var modifedMagicka = state.PatchMod.Spells.GetOrAddAsOverride(spellMagickaPerLevelGetter);


            try
            {
                if (spell.Flags.HasFlag(SpellDataFlag.NoAbsorbOrReflect))
                {
                    continue;
                }
            }
            catch
            {
                continue;
            }

            try
            {
               // Console.WriteLine(spell.CastType.ToString());
               // Console.WriteLine(spell.TargetType.ToString());

                if (spell.CastType.ToString().Equals("FireAndForget"))
                {
                    formstring = "00080A:SpellAbsorptionRework.esp";
                    if (spell.TargetType.ToString().Equals("Aimed"))
                    {
                        isagoodspell =true;
                    }
                    if (spell.TargetType.ToString().Equals("TargetLocation"))
                    {
                        isagoodspell = true;
                    }
                    if (spell.TargetType.ToString().Equals("TargetActor"))
                    {
                        isagoodspell = true;
                    }
                }
                if (spell.CastType.ToString().Equals("Concentration"))
                {
                    formstring = "00080F:SpellAbsorptionRework.esp";
                    if (spell.TargetType.ToString().Equals("Aimed"))
                    {
                        isagoodspell = true;
                    }
                    if (spell.TargetType.ToString().Equals("TargetLocation"))
                    {
                        isagoodspell = true;
                    }
                    if (spell.TargetType.ToString().Equals("TargetActor"))
                    {
                        isagoodspell = true;
                    }
                
            }
               
                if (isagoodspell == false)
                {
                    continue;
                }
                var modifiedSpell = state.PatchMod.Spells.GetOrAddAsOverride(spell);
               if (formSettings.Value.SAon)
                {
                    if (firstEffect != null)
                    {
                        var addedEffect = firstEffect.DeepCopy();
                        // Point it at your new Magic Effect instead
                        var newEffectLink = new FormLinkNullable<IMagicEffectGetter>(FormKey.Factory(formstring));

                        addedEffect.BaseEffect = newEffectLink;


                        // Optionally tweak magnitude/duration here if you want:
                        if (addedEffect.Data != null)
                        {
                            addedEffect.Data.Magnitude = 0;
                            addedEffect.Data.Duration = 1;
                            addedEffect.Data.Area = 0;
                        }
                        // Add this new effect to the spell
                        modifiedSpell.Effects.Add(addedEffect);
                    }
                }
               if (formSettings.Value.ECon == false)
                {
                    continue;
                }
                if (!string.IsNullOrEmpty(spell.EditorID) &&
    spell.EditorID.ToString().IndexOf("cloak", StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    continue; // Skip this spell entirely
                }
                if (formstring == "00080A:SpellAbsorptionRework.esp")
                {
                    var effectIds = new[]
                {
    "00092B",
    "00092A",
    "000929",
    "000928",
    "000927",
    "000926",
    "000925",
    "000924",
};

                    if (firstEffect != null)
                    {
                        foreach (var id in effectIds)
                        {
                            // Make a copy of the first effect
                            var addedEffect = firstEffect.DeepCopy();

                            // Create the FormKey for the new Magic Effect
                            var newEffectLink = new FormLinkNullable<IMagicEffectGetter>(
                                FormKey.Factory($"{id}:madEngagingCombat.esp")
                            );

                            // Assign the new BaseEffect
                            addedEffect.BaseEffect = newEffectLink;

                            // Optional modifications
                            if (addedEffect.Data != null)
                            {
                                addedEffect.Data.Magnitude = 0;
                                addedEffect.Data.Duration = formSettings.Value.debuffnum;
                                addedEffect.Data.Area = 0;
                            }
                            // Console.WriteLine("Hi");

                            // Add the effect to the spell
                            modifiedSpell.Effects.Add(addedEffect);
                        }
                    }
                }

                if (formstring == "00080F:SpellAbsorptionRework.esp")
                {
                    var effectIds = new[]
                    {
    "00093A",
    "0002BC",
    "00093B",
};

                    if (firstEffect != null)
                    {
                        foreach (var id in effectIds)
                        {
                            // Make a copy of the first effect
                            var addedEffect = firstEffect.DeepCopy();

                            // Create the FormKey for the new Magic Effect
                            var newEffectLink = new FormLinkNullable<IMagicEffectGetter>(
                                FormKey.Factory($"{id}:madEngagingCombat.esp")
                            );

                            // Assign the new BaseEffect
                            addedEffect.BaseEffect = newEffectLink;

                            // Optional modifications
                            if (addedEffect.Data != null)
                            {
                                addedEffect.Data.Magnitude = 0;
                                addedEffect.Data.Duration = 1;
                                addedEffect.Data.Area = 0;
                            }

                            // Add the effect to the spell
                            modifiedSpell.Effects.Add(addedEffect);
                        }
                    }
                }

            }
            catch (Exception ex)
            {
            }

           
        }




        foreach (var spell in state.LoadOrder.PriorityOrder.ObjectEffect().WinningOverrides())
        {
            var isagoodspell = false;
            var formstring = "00080A:SpellAbsorptionRework.esp";
            var firstEffect = spell.Effects.FirstOrDefault();
            try
            {
                if (firstEffect != null && firstEffect.Data != null)
                {
                    IFormLinkGetter<IMagicEffectGetter> effectLink = firstEffect.BaseEffect;
                    var effectLinkGetter = effectLink.Resolve(state.LinkCache);

                    // If the archetype is "Script", skip this spell entirely
                    if (effectLinkGetter.Archetype.Type.ToString() == "Script")
                    {
                        //Console.WriteLine(effectLinkGetter.Archetype.Type.ToString());
                        // Skip to the next spell
                        continue;
                    }
                    if (effectLinkGetter.Flags.HasFlag(MagicEffect.Flag.Hostile) == false)
                    {
                        continue;
                    }
                    //  Console.WriteLine(effectLinkGetter.Archetype.Type.ToString());
                }
                // At this point we KNOW we want to modify this spell

                // Make a copy of the first effect so we get its magnitude/area/duration, etc.

                if (!string.IsNullOrEmpty(spell.EditorID) &&
spell.EditorID.ToString().IndexOf("trap", StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    continue; // Skip this spell entirely
                }
            }
            catch (Exception ex)
            {
                continue;
            }



            //var spellMagickaPerLevel = new FormLink<ISpellGetter>(FormKey.Factory("0008A9:RequiemPatcherKeyword.esp"));
            //    IFormLinkGetter<ISpellRecordGetter> spellMagickaPerLevelLink = spellMagickaPerLevel;
            //    var spellMagickaPerLevelGetter = spellMagickaPerLevelLink.Resolve(state.LinkCache);
            //    var modifedMagicka = state.PatchMod.Spells.GetOrAddAsOverride(spellMagickaPerLevelGetter);



            try
            {
                // Console.WriteLine(spell.CastType.ToString());
                // Console.WriteLine(spell.TargetType.ToString());

                if (spell.CastType.ToString().Equals("FireAndForget"))
                {
                    formstring = "00080A:SpellAbsorptionRework.esp";
                    if (spell.TargetType.ToString().Equals("Aimed"))
                    {
                        isagoodspell = true;
                    }
                    if (spell.TargetType.ToString().Equals("TargetLocation"))
                    {
                        isagoodspell = true;
                    }
                    if (spell.TargetType.ToString().Equals("TargetActor"))
                    {
                        isagoodspell = true;
                    }
                }
                if (spell.CastType.ToString().Equals("Concentration"))
                {
                    formstring = "00080F:SpellAbsorptionRework.esp";
                    if (spell.TargetType.ToString().Equals("Aimed"))
                    {
                        isagoodspell = true;
                    }
                    if (spell.TargetType.ToString().Equals("TargetLocation"))
                    {
                        isagoodspell = true;
                    }
                    if (spell.TargetType.ToString().Equals("TargetActor"))
                    {
                        isagoodspell = true;
                    }

                }

                if (isagoodspell == false)
                {
                    continue;
                }
                var modifiedSpell = state.PatchMod.ObjectEffects.GetOrAddAsOverride(spell);
                if (formSettings.Value.SAon)
                {
                    if (firstEffect != null)
                    {
                        var addedEffect = firstEffect.DeepCopy();
                        // Point it at your new Magic Effect instead
                        var newEffectLink = new FormLinkNullable<IMagicEffectGetter>(FormKey.Factory(formstring));

                        addedEffect.BaseEffect = newEffectLink;


                        // Optionally tweak magnitude/duration here if you want:
                        if (addedEffect.Data != null)
                        {
                            addedEffect.Data.Magnitude = 0;
                            addedEffect.Data.Duration = 1;
                            addedEffect.Data.Area = 0;
                        }
                        // Add this new effect to the spell
                        modifiedSpell.Effects.Add(addedEffect);
                    }
                }
                // List of MagicEffect IDs you want to add
                if (formSettings.Value.ECon == false)
                {
                    continue;
                }
                if (!string.IsNullOrEmpty(spell.EditorID) &&
    spell.EditorID.ToString().IndexOf("cloak", StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    continue; // Skip this spell entirely
                }
                if (formstring == "00080A:SpellAbsorptionRework.esp")
                {
                    var effectIds = new[]
                {
    "00092B",
    "00092A",
    "000929",
    "000928",
    "000927",
    "000926",
    "000925",
    "000924",
};

                if (firstEffect != null)
                {
                    foreach (var id in effectIds)
                    {
                        // Make a copy of the first effect
                        var addedEffect = firstEffect.DeepCopy();

                        // Create the FormKey for the new Magic Effect
                        var newEffectLink = new FormLinkNullable<IMagicEffectGetter>(
                            FormKey.Factory($"{id}:madEngagingCombat.esp")
                        );

                        // Assign the new BaseEffect
                        addedEffect.BaseEffect = newEffectLink;

                        // Optional modifications
                        if (addedEffect.Data != null)
                        {
                            addedEffect.Data.Magnitude = 0;
                                addedEffect.Data.Duration = formSettings.Value.debuffnum;
                                addedEffect.Data.Area = 0;
                            }
                            //Console.WriteLine("Hi");

                            // Add the effect to the spell
                            modifiedSpell.Effects.Add(addedEffect);
                    }
                }
            }

                if (formstring == "00080F:SpellAbsorptionRework.esp")
                {
                    var effectIds = new[]
                    {
    "00093A",
    "0002BC",
    "00093B",
};

                    if (firstEffect != null)
                    {
                        foreach (var id in effectIds)
                        {
                            // Make a copy of the first effect
                            var addedEffect = firstEffect.DeepCopy();

                            // Create the FormKey for the new Magic Effect
                            var newEffectLink = new FormLinkNullable<IMagicEffectGetter>(
                                FormKey.Factory($"{id}:madEngagingCombat.esp")
                            );

                            // Assign the new BaseEffect
                            addedEffect.BaseEffect = newEffectLink;

                            // Optional modifications
                            if (addedEffect.Data != null)
                            {
                                addedEffect.Data.Magnitude = 0;
                                addedEffect.Data.Duration = 1;
                                addedEffect.Data.Area = 0;
                            }

                            // Add the effect to the spell
                            modifiedSpell.Effects.Add(addedEffect);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
            }


        }






    }
}
